// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function DestinationInfo(arg1) {
  return window['go']['main']['App']['DestinationInfo'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function IsDevSafe() {
  return window['go']['main']['App']['IsDevSafe']();
}

export function IsElevated() {
  return window['go']['main']['App']['IsElevated']();
}

export function ListDisks() {
  return window['go']['main']['App']['ListDisks']();
}

export function PickImage() {
  return window['go']['main']['App']['PickImage']();
}

export function PickSaveFile(arg1) {
  return window['go']['main']['App']['PickSaveFile'](arg1);
}

export function ReadImageInfo(arg1) {
  return window['go']['main']['App']['ReadImageInfo'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function StartClone(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartClone'](arg1, arg2, arg3);
}

export function StartImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartImage'](arg1, arg2, arg3);
}

export function StartRestoreImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartRestoreImage'](arg1, arg2, arg3);
}
