// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mount} from '../models';
import {main} from '../models';
import {disk} from '../models';
import {image} from '../models';

export function Cancel():Promise<void>;

export function DestinationInfo(arg1:string):Promise<mount.Info>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetConfig():Promise<main.Config>;

export function IsDevSafe():Promise<boolean>;

export function IsElevated():Promise<boolean>;

export function ListDisks():Promise<Array<disk.Disk>>;

export function PickImage():Promise<string>;

export function PickSaveFile(arg1:string):Promise<string>;

export function ReadImageInfo(arg1:string):Promise<image.Info>;

export function SetLanguage(arg1:string):Promise<void>;

export function StartClone(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function StartImage(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function StartRestoreImage(arg1:string,arg2:string,arg3:boolean):Promise<void>;
