// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function DestinationInfo(arg1) {
  return window['go']['main']['App']['DestinationInfo'](arg1);
}

export function EstimateArchive(arg1, arg2) {
  return window['go']['main']['App']['EstimateArchive'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function IsDevSafe() {
  return window['go']['main']['App']['IsDevSafe']();
}

export function IsElevated() {
  return window['go']['main']['App']['IsElevated']();
}

export function ListDisks() {
  return window['go']['main']['App']['ListDisks']();
}

export function PickArchive() {
  return window['go']['main']['App']['PickArchive']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PickSaveFile(arg1) {
  return window['go']['main']['App']['PickSaveFile'](arg1);
}

export function ReadArchiveInfo(arg1) {
  return window['go']['main']['App']['ReadArchiveInfo'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function StartArchive(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartArchive'](arg1, arg2, arg3);
}

export function StartClone(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartClone'](arg1, arg2, arg3);
}

export function StartRestore(arg1, arg2) {
  return window['go']['main']['App']['StartRestore'](arg1, arg2);
}
